### ISSUE TITLE
'Icon' was called on null

### ISSUE THREAD

**Issue by aissahadjsaid** [undrbridge/curved_drawer#1]
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building CurvedDrawer(dirty, dependencies: [Directionality, MediaQuery], state: _CurvedDrawerState#8b6a1(ticker inactive)):
The getter 'icon' was called on null.
Receiver: null
Tried calling: icon

The relevant error-causing widget was: 
  CurvedDrawer file:///D:/workspace/flutter/projects/kf_drawer/lib/main.dart:75:18
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      _CurvedDrawerState.build.<anonymous closure> (package:curved_drawer/curved_drawer.dart:180:34)
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:29)
#3      ListIterable.toList (dart:_internal/iterable.dart:221:19)
#4      _CurvedDrawerState.build (package:curved_drawer/curved_drawer.dart:182:22)

**Comment by suo801** [comment]
i had the same question,and  had emil writer

**Comment by suo801** [comment]
by the way have you resolved this ?

**Comment by undrbridge** [comment]
I have not, been working on other items. I'll address when when I get a chance.

Sent from my iPhone

On Mar 27, 2020, at 10:40 AM, suo801 <notifications@github.com> wrote:

﻿

by the way have you resolved this ?

**Comment by suo801** [comment]
Thank you. I will keep an eye on the results. And I'm working on it myself

**Comment by suo801** [comment]
wow,i just resolved.i made it! 我去掉了列表赋值
//    _items = widget.items.map((item) {
//      DrawerNavItem(
//        icon: item.icon,
//        label: item.label,
//        color: widget.labelColor,
//        background: widget.buttonBackgroundColor,
//        size: widget.width / 3,
//      );
//    }).toList();
下面直接用widget.items，而不用_items，因为这里循环赋值有问题。

**Comment by AbdulrhmanAlani96** [comment]
Hi there , it's not work @suo801 , do you have another solve for it ?

**Comment by vilain-corentin** [comment]
In curved_drawer.dart,
`List<DrawerNavItem> _items = [];`

replace to map by :

```
widget.items.forEach((item) {
      _items.add(DrawerNavItem(
        icon: item.icon,
        label: item.label,
        color: widget.labelColor,
        background: widget.buttonBackgroundColor,
        size: widget.width / 3,
      ));
    });
```

**Comment by MarcoSchneider123** [comment]
Thank you vilain-corentin, i had the same issue and this resolved my issue

**Comment by sheen404** [comment]
It isn't working. Is there any other way to solve this?

**Comment by DmitiryKd2** [comment]
1. first  - in file "curved_drawer.dart" line №65 init _items like this -  List<DrawerNavItem> _items = new List<DrawerNavItem>();
2. second - from line 70 to 78 delete this code
  _items = widget.items.map((item) {
      DrawerNavItem(
        icon: item.icon,
        label: item.label,
        color: widget.labelColor,
        background: widget.buttonBackgroundColor,
        size: widget.width / 3,
      );
    }).toList();
3 replece like this:
for(var item in widget.items){
        final navItem = new DrawerNavItem(
        icon: item.icon,
        label: item.label,
        color: widget.labelColor,
        background: widget.buttonBackgroundColor,
        size: widget.width / 3,
      );     
      _items.add(navItem);
    }
for me it works

**Comment by tanzilzubair** [comment]
It isn't working, is there another way to solve this?

**Comment by Sankalp1902** [comment]
None of them are working :(

**Comment by drmspatil** [comment]
> In curved_drawer.dart,
> `List<DrawerNavItem> _items = [];`
> 
> replace to map by :
> 
> ```
> widget.items.forEach((item) {
>       _items.add(DrawerNavItem(
>         icon: item.icon,
>         label: item.label,
>         color: widget.labelColor,
>         background: widget.buttonBackgroundColor,
>         size: widget.width / 3,
>       ));
>     });
> ```

Not Working

**Comment by sonOfwidgets** [comment]
#5 Put a return statement or replace it with arrow function

**Comment by gizemgizg** [comment]
Anyone find the solution? :/

**Comment by sollylabs** [comment]
Please write the whole updated code.

**Comment by sollylabs** [comment]
> In curved_drawer.dart,
> `List<DrawerNavItem> _items = [];`
> 
> replace to map by :
> 
> ```
> widget.items.forEach((item) {
>       _items.add(DrawerNavItem(
>         icon: item.icon,
>         label: item.label,
>         color: widget.labelColor,
>         background: widget.buttonBackgroundColor,
>         size: widget.width / 3,
>       ));
>     });
> ```

Please write the whole code

**Comment by kamal0s** [comment]
just change code in the line just like this photo that will resolve problem 
https://ibb.co/h20k2cc

**Comment by Vishesht** [comment]
Use custom code
https://github.com/Riya28042000/curved_drawer/blob/master/pubspec.yaml

**Comment by Vishesht** [comment]
This flutter dependency is  showing error.
Use the Custom Curve Drawer in Flutter 
**Git hub Link** :- https://github.com/Vishesht/Curved-Drawer-Flutter

**Comment by 5hanth** [comment]
+1 https://github.com/undrbridge/curved_drawer/issues/1#issuecomment-612453034 works well on local. can we expect this patch to get released? currently, this plugin is unusable on CI builds that download packages on app center which won't have this patch.

**Comment by gopaltalaviya** [comment]
Fixed with simple solution is that 
Code:
```
 _items = widget.items.map((item) {
      DrawerNavItem(
        icon: item.icon,
        label: item.label,
        color: widget.labelColor,
        background: widget.buttonBackgroundColor,
        size: widget.width / 3,
      );
    }).toList();

```

Replace with 👍 
Add return statement 

```
_items = widget.items.map((item) {
      return DrawerNavItem(
        icon: item.icon,
        label: item.label,
        color: widget.labelColor,
        background: widget.buttonBackgroundColor,
        size: widget.width / 3,
      );
    }).toList();

```
